# Generated by Django 5.0.2 on 2024-03-01 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recess', '0004_feed_feed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_original_importer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_feeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feed',
            name='feed_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_feeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='feeds_following',
            field=models.ManyToManyField(blank=True, related_name='feeds_following', to='recess.feed'),
        ),
    ]
