# Generated by Django 5.0.2 on 2024-03-06 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recess', '0010_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_last_publish',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
