# Generated by Django 5.0.2 on 2024-03-07 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recess', '0011_feed_feed_last_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_last_publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
