# Generated by Django 5.0.2 on 2024-03-08 11:17

import recess.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recess", "0012_alter_feed_feed_last_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="feed_picture_url",
            field=recess.models.URLField(blank=True, max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name="feed",
            name="feed_url",
            field=recess.models.URLField(max_length=2083, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_url",
            field=recess.models.URLField(max_length=2083),
        ),
    ]
