# Generated by Django 5.0.2 on 2024-03-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recess', '0013_alter_feed_feed_picture_url_alter_feed_feed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
