# Generated by Django 5.0.2 on 2024-03-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recess', '0014_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_status',
            field=models.IntegerField(default=0),
        ),
    ]
