# Generated by Django 5.0.2 on 2024-03-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recess', '0015_remove_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_publisher_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_name',
            field=models.CharField(max_length=500),
        ),
    ]
