# Generated by Django 5.0.2 on 2024-03-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recess', '0016_feed_feed_publisher_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
