# Generated by Django 5.0.2 on 2024-03-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recess', '0017_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('lock_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('owner_process_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
