# Generated by Django 5.0.2 on 2024-03-16 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recess', '0018_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='lock_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 1, 15, 5, 763663)),
        ),
    ]
