# Generated by Django 5.0.2 on 2024-03-16 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recess', '0019_lock_lock_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='lock_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 1, 20, 42, 859401, tzinfo=datetime.timezone.utc)),
        ),
    ]
