# Generated by Django 5.0.2 on 2024-03-22 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recess', '0020_alter_lock_lock_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='hide_from_discovery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lock',
            name='lock_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 13, 8, 11, 100818, tzinfo=datetime.timezone.utc)),
        ),
    ]
