# Generated by Django 5.0.2 on 2024-03-22 13:09

import recess.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recess', '0021_feed_hide_from_discovery_alter_lock_lock_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='lock_expiry',
            field=models.DateTimeField(default=recess.models.lock_expiry_default),
        ),
    ]
