# Generated by Django 5.0.2 on 2024-02-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='feeds_following',
            field=models.ManyToManyField(blank=True, to='backend.feed'),
        ),
    ]
