# Generated by Django 5.0.2 on 2024-02-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_feed_feed_name_alter_feed_feed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
